config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  get 'home/index'

  resources :members 

  resources :cetyas

  resources :events 

  resources :attendances

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'members#index'
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances
    has_many :members, through: :attendances, dependent: :destroy
    has_one_attached :cover
    
    validates :name, presence: true, length: {minimum:3}
    validates :start_date, presence: true
    validates :location, presence: true
    validate :acceptable_image

    def acceptable_image
        return unless cover.attached?
        
        unless avatar.byte_size <= 5.megabyte
            errors.add(:avatar, "Ukuran gambar terlalu besar")
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  def index
      # @events = Event.all
      @q = Event.ransack(params[:q])
      @q.sorts = "start_date desc" if @q.sorts.empty?
      @events = @q.result.paginate(page: params[:page], per_page: 4)
  end
  
  def new
      @event = Event.new
  end
  
  def create
      @event = Event.new(event_params)
      if @event.save
        flash[:success] = "Event successfully created"
        redirect_to events_path
      else
        flash[:error] = "Something went wrong"
        render 'new'
      end
  end

  def show
      @event = Event.find(params[:id])
      @members = Member.select(:id, :name)
      @attendance = Attendance.select("attendances.*, members.name, members.id AS member_id").
                              joins("JOIN members ON attendances.member_id = members.id").
                              where("attendances.event_id = ?", @event.id).distinct
      @attendance_number = Attendance.where("event_id = ?", @event.id).distinct.count
  end
  
  def edit
      @event = Event.find(params[:id])
  end
  
  def update
      @event = Event.find(params[:id])
      if @event.update_attributes(event_params)
        flash[:success] = "Event was successfully updated"
        redirect_to events_path
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end

  def destroy
      @event = Event.find(params[:id])
      if @event.destroy
          flash[:success] = 'Event was successfully deleted.'
          redirect_to events_url
      else
          flash[:error] = 'Something went wrong'
          redirect_to events_url
      end
  end
  
  
  
  private

  def event_params
      params.require(:event).permit(:name, :start_date, :location, :attendee_number, :cover)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event, defaults: { wrapper_html: { class: 'row' } } do |f| %>
    <%= f.input :name,
        label: "Nama Acara",
        error: "Nama Acara harus diisi!" %>
    <%= f.input :start_date,
        label: "Tanggal Acara",
        error: "Tanggal Acara harus diisi!",
        as: :string,
        input_html: { class: "datepicker" } %>
    <%= f.input :location,
        label: "Lokasi Acara",
        error: "Lokasi Acara harus diisi!" %>
    <!-- <%= f.input :cover, 
        as: :file,
        label: "Cover/Art (max. 5MB): ",
        input_html: { class: "btn-file", accept: "image/*" } %> -->
    <%= f.button :submit, "Simpan Data", class: "btn-margin-r-10" %>
    <%= f.button :button, "Hapus Formulir", 
        type: :reset, class: "btn btn-danger" %>
<% end %>

app/views/events/_search_form.html.erb
<%= search_form_for @q do |f| %>
    <div class="col l6">
        <%= f.search_field :name_cont, class: "form-control", placeholder: "Nama" %>
    </div>
    <div class="col l12">
        <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/events/edit.html.erb
<div class="container">
    <div class="row">
        <h4>Perubahan Data Acara</h4>
    </div>
    <%= render  "form" %>
</div>

app/views/events/index.html.erb
<div class="container">
    <div class="row">
        <%= link_to new_event_path, class: "add-event btn tooltipped", data: { tooltip: "Tambah Acara", position: "left" } do %>
            <i class="material-icons"> add </i>
        <% end %>
    </div>
    <div class="row">
        <%= render  "search_form" %>
    </div>
    <div class="row">
        <% if @events.blank? %>
            <b>No data found!</b>
        <% else %>
        <div class="flex-container">
            <% @events.each do |e| %>
                <% attendance_number = Attendance.where("event_id = ?", e.id).distinct.count %>
                <div class="flex-content-events tooltipped" data-tooltip="Klik Nama Acara untuk lihat detail">
                    <p class="name">
                        <b><%= link_to event_path(e) do %><%= e.name %><% end %></b>
                    </p>
                    <p class="date-att-num">
                        <span class="start-date"><%= e.start_date.strftime("%d %B %Y") %></span>
                        <span class="att-num right">Jumlah yang hadir: <%= attendance_number %> orang</span>
                    </p>
                    <p class="loc actions">
                        <span class="loc">
                            <%= e.location %>
                        </span>
                        <span class="delete right">
                            <%= link_to event_path(e), method: :delete, data: { confirm: 'Are you sure?' } do %>
                                <i class="material-icons">delete_forever</i>
                            <% end %>
                        </span>
                        <span class="edit right" style="margin-right: 10px;">
                            <%= link_to edit_event_path(e) do %>
                                <i class="material-icons">edit</i>
                            <% end %>
                        </span>
                    </p>
                </div>                
            <% end %>
        </div>
        <% end %>
    </div>
    <div class="row">
        <%= will_paginate @events %>
    </div>
</div>

app/views/events/new.html.erb
<div class="container">
    <div class="row">
        <h4>Pengisian Data Baru Acara</h4>
    </div>
    <%= render  "form" %>
</div>

app/views/events/show.html.erb
<div class="container">
    <div class="row show-title">
        <h5><%= @event.name %></h5>
        <div class="divider"></div>
    </div>
    <% if @event.cover.attached? %>
        <div class="row">
            <img class="event-cover" src="<%= (url_for(@event.cover)) %>" alt="">
        </div>
    <% end %>
    <div class="row">
        <span class="col l4">Tanggal Acara: </span>
        <span class="col l8">: <%= @event.start_date %></span>
    </div>
    <div class="row">
        <span class="col l4">Lokasi Acara: </span>
        <span class="col l8">: <%= @event.location %></span>
    </div>
    <div class="row">
        <span class="col l4">Jumlah Kehadiran: </span>
        <span class="col l8">: <%= @attendance_number %></span>
    </div>
    <div class="row">
        <div class="divider"></div>
    </div>
    <div class="row">
        <span>Data Kehadiran: </span>
    </div>
    <div class="flex-container">
        <% @attendance.each do |a| %>
            <div class="flex-content-members tooltipped" data-tooltip="Klik Nama untuk lihat detail">
                <p class="name">
                    <%= link_to member_path(a.member_id) do %><%= a.name %><% end %>
                </p>
            </div>                
        <% end %>
    </div>

</div>