config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  get 'home/index'

  resources :members 

  resources :cetyas

  resources :events 

  resources :attendances

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'members#index'
end

app/models/cetya.rb
class Cetya < ApplicationRecord
    has_many :members
    validates :cetya_name, presence: true
end

app/controllers/cetyas_controller.rb
class CetyasController < ApplicationController
  before_action :authenticate_user!
  def index
      @cetyas = Cetya.all
  end
  
  def new
      @cetya = Cetya.new
  end
  
  def create
      @cetya = Cetya.new(cetya_params)
      if @cetya.save
        redirect_to cetyas_path
      else
        render 'new'
      end
  end

  def show
      @cetya = Cetya.find(params[:id])
  end

  def edit
      @cetya = Cetya.find(params[:id])
  end
  
  def update
      @cetya = Cetya.find(params[:id])
      if @cetya.update_attributes(cetya_params)
        redirect_to cetyas_path
      else
        render 'edit'
      end
  end
  
  def destroy
      @cetya = Cetya.find(params[:id])
      if @cetya.destroy
          redirect_to cetyas_url
      else
          redirect_to cetyas_url
      end
  end
  
  private

  def cetya_params
      params.require(:cetya).permit(:cetya_name)
  end
end

app/helpers/cetyas_helper.rb
module CetyasHelper
end

app/views/cetyas/_form.html.erb
<%= simple_form_for @cetya, defaults: { wrapper_html: { class: 'row' } } do |f| %>
    <%= f.input :cetya_name,
        label: "Name Cetya",
        error: "Nama Cetya harus diisi!" %>
    <%= f.button :submit, "Simpan Data", class: "btn-margin-r-10" %>
<% end %>

app/views/cetyas/edit.html.erb
<div class="container">
    <div class="row">
        <h4>Perubahan Data Cetya</h4>
    </div>
    <%= render  "form" %>
</div>

app/views/cetyas/index.html.erb
<div class="container">
    <div class="row">
        <%= link_to new_cetya_path, class: "add-ctya btn tooltipped", data: { tooltip: "Tambah Cetya baru", position: "left" } do %>
            <i class="material-icons"> add </i>
        <% end %>
    </div>
    <div class="row">
        Daftar cetya-cetya yang ada
    </div>
    <% if @cetyas.blank? %>
        <div class="row">
            <div class="col l12 cetya-container">Data Kosong</div>
        </div>
    <% else %>
        <div class="row">
        <% @cetyas.each do |c| %>
            <div class="col l12 cetya-container tooltipped" data-tooltip="Klik Nama Cetya untuk ubah nama">
                <div class="cetya-data">
                    <%= link_to edit_cetya_path(c) do %><%= c.cetya_name %> <% end %>
                    <span class="right">
                        <%= link_to cetya_path(c), method: :delete, data: { confirm: 'Are you sure?' },
                            class: "btn btn-danger" do %>
                                <i class="material-icons">delete_forever</i>
                            <% end %>
                    </span>
                </div>
            </div>
        <% end %>
        </div>
    <% end %>
</div>

app/views/cetyas/new.html.erb
<div class="container">
    <div class="row">
        <h4>Pengisian Data Baru Cetya</h4>
    </div>
    <%= render  "form" %>
</div>