config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  get 'home/index'

  resources :members 

  resources :cetyas

  resources :events 

  resources :attendances

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'members#index'
end

app/views/layouts/_footer.html.erb
<div class="footer-copyright footer-custom">
  <div class="container center-align">
    © 2020 Albert Harican. All rights reserved. GNU GPL-3.0 License.
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="nav-wrapper">   
    <ul class="left">
        <li class="logo">
            <%= link_to home_index_path do %>
                <img src="/images/GM_Record.svg" alt="ERROR LOADING IMAGE" style="width: 50px; padding-top: 10px;" >
            <% end %>
        </li>
        <li class="app-name">
            <%= link_to  "GM Medan Portal", members_path %>
        </li>
        <!-- <li class="home nav-menu <%= is_active?("home") %>">
            <%= link_to  "Beranda", home_index_path %>
        </li> -->
        <li class="gm-data nav-menu <%= is_active?("members") %>">
            <%= link_to  "Data GM", members_path %>
        </li>
        <li class="event-data nav-menu <%= is_active?("events") %>">
            <%= link_to  "Data Acara", events_path %>
        </li>
        <li class="event-data nav-menu <%= is_active?("attendances") %>">
            <%= link_to  "Data Kehadiran", new_attendance_path %>
        </li>
        <li class="other-data nav-menu dropdown-trigger" data-target="dropdown1">
            <a href="#">Data lainnya</a>
            <ul id="dropdown1" class="dropdown-content">
                <li><%= link_to  "Data Cetya", cetyas_path %></li>
            </ul>
        </li>
    </ul>
    <% if user_signed_in? %>
      <ul class="right">
        <li>
            <span><%= current_user.email %></span>
        </li>
        <li>
          <%= link_to  "Keluar", destroy_user_session_path, 
              method: :delete , class: "nav-menu-btn btn red darken-4" %>
        </li>
      </ul>
    <% else %>
      <ul class="right">
          <li>
            <%= link_to  "Daftar", user_registration_path, 
                class: "nav-menu-btn btn regis-button" %>
          </li>
          <li>
            <%= link_to  "Masuk", new_user_session_path, 
                class: "nav-menu-btn btn sign-in-button" %>
          </li>
      </ul>
    <% end %>
</div>

app/views/layouts/_scripts.html.erb
<script>
    function phoneNumCheck(e) {
        var input = e.key
        var regex = /([^\d+])/
        if (regex.test(input) && e.which != 8) {
            e.preventDefault()
        }
    };

    $(document).ready(function(){
        // Dropdown menu
        $('select').formSelect();

        // Date picker.
        var thisYear = new Date().getFullYear()
        $('.datepicker').datepicker({
            yearRange: [thisYear - 50, thisYear]
        });

        $('.tooltipped').tooltip({
            enterDelay: 200,
        });

        $('.dropdown-trigger').dropdown();

        $('.timepicker').timepicker({
            twelveHour: false
        });
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="shortcut icon" href="/images/GM_Record.svg" type="image/x-icon">
    <title>Pendataan GM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
  <header>
    <div class="navbar-fixed">
      <nav>
        <%= render  "layouts/header" %>
      </nav>
    </div>
  </header>
  <main>
    <%= yield %>
  </main>
  <footer>
    <%= render "layouts/footer"%>
  </footer>

  <%= render "layouts/scripts" %>
  </body>
</html>