config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  get 'home/index'

  resources :members 

  resources :cetyas

  resources :events 

  resources :attendances

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'members#index'
end

app/models/member.rb
class Member < ApplicationRecord
    belongs_to :cetya
    has_many :attendances
    has_many :events, through: :attendances, dependent: :destroy
    has_one_attached :avatar

    validates :name, presence: true, length: {minimum:3}
    validates :gender, presence: true
    validate :acceptable_image

    def acceptable_image
        return unless avatar.attached?
        
        unless avatar.byte_size <= 5.megabyte
            errors.add(:avatar, "Ukuran gambar terlalu besar")
        end
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!
  
  def index
      @q = Member.ransack(params[:q])
      # @members = Member.select("members.*, cetyas.cetya_name")
      #                  .joins("JOIN cetyas ON members.cetya_id = cetyas.id ")
      @q.sorts = "name asc" if @q.sorts.empty?
      @members = @q.result(disctinct: true)
                   .includes(:cetya)
                   .paginate(page: params[:page], per_page: 12)
                   
      @members.each do |m|
          m.age = change_date_null(m.date_of_birth)
      end
  end

  def new
      @member = Member.new
  end

  def create
      @member = Member.new(member_params)
      
      if @member.date_of_birth.blank?
          @member.age = "-"
      else
          @member.age = age_counter(@member.date_of_birth)
      end

      if @member.save
        redirect_to members_path
      else
        render 'new'
      end
  end

  def show
      @member = Member.select("members.*, cetyas.cetya_name")
                      .joins("JOIN cetyas ON members.cetya_id = cetyas.id")
                      .find(params[:id])
      @member.age = change_date_null(@member.date_of_birth)
      @member.place_of_birth = change_null_to_hyphen(@member.place_of_birth)
      @member.phone = change_null_to_hyphen(@member.phone)
      @member.address = change_null_to_hyphen(@member.address)
      @member.line_id = change_null_to_hyphen(@member.line_id)

      @events_attended = Attendance.select("attendances.*, events.name")
                               .joins("JOIN members ON members.id = attendances.member_id")
                               .joins("JOIN events ON events.id = attendances.event_id")
                               .where("members.id = ?", @member.id)
                               .order("events.start_date DESC")
  end

  def edit
      @member = Member.find(params[:id])
  end
  
  def update
      @member = Member.find(params[:id])
      if @member.date_of_birth.blank?
        @member.age = "-"
      else
        @member.age = age_counter(@member.date_of_birth)
      end
      if @member.update_attributes(member_params)
        redirect_to @member
      else
        render 'edit'
      end
  end
  
  def destroy
      
      @member = Member.find(params[:id])
      if @member.destroy
          redirect_to members_path
      else
          redirect_to members_url
      end
  end
  

  private

  def member_params
      params.require(:member).permit(:name, :phone, :address, :cetya_id,
                                      :gender, :education, :date_of_birth,
                                      :place_of_birth, :line_id, :avatar)
  end

  def age_counter(dob)
      now = Time.now.utc.to_date
      now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

  def change_null_to_hyphen(param)
      if param.blank? 
          param = "-"
      else
          param = param
      end
  end

  def change_date_null(dob)
      if dob.blank?
          age = "-"
      else
          age = age_counter(dob)
      end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= simple_form_for @member, defaults: { wrapper_html: { class: 'row' } } do |f| %>
    <%= f.input :name,
        label: "Nama",
        error: "Nama tidak boleh kosong!" %>
    <%= f.input :phone,
        label: "Nomor Telepon",
        input_html: { onkeydown: "phoneNumCheck(event)" } %>
    <%= f.input :address,
        label: "Alamat" %>
    <%= f.association  :cetya, 
        label: "Cetya",
        error: "Harus dipilih",
        collection: Cetya.all.order(:cetya_name),
        label_method: :cetya_name,
        prompt: "-Pilih Cetya-" %>
    <%= f.input :gender,
        label: "Jenis Kelamin", 
        as: :select,
        prompt: "-Pilih Jenis Kelamin-",
        collection: [["Laki-Laki", "Laki-Laki"], 
                    ["Perempuan", "Perempuan"], ["Lainnya", "Lainnya"]],
        error: "Tidak boleh kosong!" %>
    <%= f.input :education,
        label: "Pendidikan" %>
    <%= f.input :line_id,
        label: "ID Line"%>
    <%= f.input :place_of_birth, 
        label: "Tempat Lahir" %>
    <%= f.input :date_of_birth, 
        label: "Tanggal Lahir", 
        as: :string,
        input_html: { class: "datepicker" } %>
    <!-- <%= f.input :avatar, 
        as: :file,
        label: "Foto (max. 5MB)",
        input_html: { class: "btn-file", accept: "image/*" } %> -->
    <%= f.button :submit, "Simpan Data", class: "btn-margin-r-10" %>
    <%= f.button :button, "Hapus Formulir", 
        type: :reset, class: "btn btn-danger" %>
<% end %>

app/views/members/_search_form.html.erb
<%= search_form_for @q do |f| %>
    <div class="col l6">
        <%= f.search_field :name_cont, class: "form-control", placeholder: "Nama" %>
    </div>
    <div class="col l6">
        <%= f.search_field :cetya_cetya_name_cont, class: "form-control", placeholder: "Cetya" %>
    </div>
    <div class="col l12">
        <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/members/edit.html.erb
<div class="container">
    <div class="row">
        <h4>Perubahan Data Baru GM</h4>
    </div>
    <%= render  "form" %>
</div>

app/views/members/index.html.erb
<div class="container">
    <div class="row">
        <%= link_to new_member_path, class: "add-member btn tooltipped", data: { tooltip: "Add new member", position: "left" } do %>
            <i class="material-icons"> add </i>
        <% end %>
    </div>
    <div class="row">
        <%= render  "search_form" %>
    </div>
    <div class="row">
        <% if @members.blank? %>
            No data found!
        <% else %>
        <div class="flex-container">
            <% @members.each do |m| %>
                <div class="flex-content-members tooltipped" data-tooltip="Klik Nama untuk lihat detail">
                    <p class="name">
                        <b><%= link_to member_path(m) do %><%= m.name %><% end %></b>
                    </p>
                    <p class="gender-age">
                        <span class="gender"><%= m.gender %></span>
                        <span class="age right"><%= m.age %></span>
                    </p>
                </div>                
            <% end %>
        </div>
        <% end %>
    </div>
    <div class="row">
        <%= will_paginate @members %>
    </div>
</div>

app/views/members/new.html.erb
<div class="container">
    <div class="row">
        <h4>Pengisian Data Baru GM</h4>
    </div>
    <%= render  "form" %>
</div>

app/views/members/show.html.erb
<div class="container">
    <div class="row show-title">
        <h5><%= @member.name %></h5>
        <div class="divider"></div>
    </div>
    <div class="row buttons">
        <%= link_to edit_member_path, class: "btn btn-margin-r-10" do %>
            <i class="material-icons">edit</i>
        <% end %>
        <%= link_to member_path, method: :delete, data: { confirm: 'Are you sure?' },
        class: "btn btn-danger" do %>
            <i class="material-icons">delete_forever</i>
        <% end %>
    </div>
    <div class="row">
        <div class="col l6">
            <div class="row">
                <span class="col l4">Cetya</span>
                <span class="col l8">: <%= @member.cetya_name %></span>
            </div>
            <div class="row">
                <span class="col l4">Jenis Kelamin</span>
                <span class="col l8">: <%= @member.gender %></span>
            </div>
            <div class="row">
                <span class="col l4">Tempat dan Tanggal Lahir</span>
                <span class="col l8">: <%= @member.place_of_birth %>, <%= @member.date_of_birth.blank? ? "-" : @member.date_of_birth.strftime("%d-%b-%Y")  %></span>
            </div>
            <div class="row">
                <span class="col l4">Umur</span>
                <span class="col l4">: <%= @member.age %></span>
            </div>
            <div class="row">
                <span class="col l4">Nomor HP</span>
                <span class="col l8">: <%= @member.phone %></span>
            </div>
            <div class="row">
                <span class="col l4">Alamat</span>
                <span class="col l8">: <%= @member.address %></span>
            </div>
            <div class="row">
                <span class="col l4">Pendidikan terakhir</span>
                <span class="col l4">: <%= @member.education %></span>
            </div>
            <div class="row">
                <span class="col l4">ID Line</span>
                <span class="col l8">: <%= @member.line_id %></span>
            </div>
        </div>
        <% if @member.avatar.attached? %>
            <div class="col l6">
                <img class="member-avatar" src="<%= (url_for(@member.avatar)) %>" alt="">
            </div>
        <% end %>
    </div>
    <div class="row">
        <div class="divider"></div>
    </div>
    <div class="row">
        <span>Data Kehadiran: </span>
    </div>
    <div class="flex-container">
        <% @events_attended.each do |e| %>
            <div class="flex-content-members tooltipped" data-tooltip="Klik Nama Acara untuk lihat detail">
                <p class="name">
                    <%= link_to event_path(e.event_id) do %><%= e.name %><% end %>
                </p>
            </div>                
        <% end %>
    </div>
</div>